import { task1 } from "./demo/task1";
import { task2 } from "./demo/task2";
import { task3 } from "./demo/task3";
import { task4 } from "./demo/task4";
import { task5 } from "./demo/task5";
import { task6 } from "./demo/task6";
import { task7 } from "./demo/task7";

// console.log("\n========================= TASK 1 ============================");
// task1();
// console.log("\n========================= TASK 2 ============================");
// task2();
// console.log("\n========================= TASK 3 ============================");
// task3();
// console.log("\n========================= TASK 4 ============================");
// task4();
// console.log("\n========================= TASK 5 ============================");
// task5();
// console.log("\n========================= TASK 6 ============================");
// task6();
// console.log("\n========================= TASK 7 ============================");
// task7();
